name: Lint

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: py-actions/flake8@v2
