name: Unittest

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run tests
        run: |
          find ./tests/ -name 'test_*.py' | xargs python -m unittest
